require 'active_support/all'
require 'farscape/dice_bag/template'
require 'farscape/configuration'
require 'farscape/agent'
require 'farscape/config_file'
require 'farscape/simple_agent'
require 'farscape/discovery_client'
require 'farscape/programming_api'
